#!/bin/sh
set -e

mkdir $BUILD_DIR
cd $BUILD_DIR

CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DSLEIPNIR_SHLIBDEPS=OFF"

cmake $CMAKE_FLAGS ..

make -j${nproc} package
